name: Build homeserver image

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  image:
    uses: jerematix-homelab/homeserver-actions/.github/workflows/build-local-image.yaml@v1
    with:
      dockerfile: Dockerfile.ghcr
      image: homeserver/ha-mcp
